data_path:
  train_data : C:\Users\win10\Desktop\New folder (6)\CNN_for_disease_detection\app\dataset\train
  test_data : C:\Users\win10\Desktop\New folder (6)\CNN_for_disease_detection\app\dataset\test
